### ISSUE TITLE
Add support for new Zapier workflow

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1287]
**Description**
Zapier is now fully setup in Zapier and not in Gravity Forms. We need to ensure the PDF URLs are passed along and available for processing

**Comment by jakejackson1** [comment]
The appropriate filter needed to support Gravity PDF [was added in Zapier 4.1.1](https://docs.gravityforms.com/zapier-change-log/#4-1-1).

**Comment by fabwintle** [comment]
Would love to see this happen :)

**Comment by jakejackson1** [comment]
@jestonihpi this is a key feature I would like added in the next minor release.

**Comment by jakejackson1** [comment]
See https://github.com/GravityPDF/image-hopper/pull/99/files for a working example of using the `gform_zapier_request_body` filter.
