### ISSUE TITLE
Notification shows up for only a fraction of a second when applying any changes to the form's PDF settings

### ISSUE THREAD

**Issue by XSFN-07** [blueliquiddesigns/gravity-forms-pdf-extended#1288]
**Description**
When applying any changes to the form's PDF settings, the success notification on the top portion of the page shows up very quickly, and then it disappears -- giving a little chance for the user to confirm that the changes made were successfully applied (or not), which could affect the overall UX.

**Step To Reproduce**
1. From the WordPress Dashboard, go to _Forms_.
2. On any active forms, hover on _Settings_ and click on _PDF_.
3. Either _Add New_ PDF or _Edit_ an existing PDF from the list.
4. Apply any changes to the settings by clicking on _Update PDF_.
5. The page will then scroll to the top and show a notification confirming that the changes were made, but only for a fraction of a second.

**Expected behavior**
The notification should remain visible on top of the page unless manually dismissed by the user, or after a reasonable amount of time / duration.

**Screenshots**
Please see the attached file herewith.

https://user-images.githubusercontent.com/41829337/119420466-28c45480-bd2f-11eb-9b67-00adfe6738fe.mp4

**Comment by jakejackson1** [comment]
Resolved
