### ISSUE TITLE
Upload with Merge-tag

### ISSUE THREAD

**Issue by mcglenn07** [blueliquiddesigns/gravity-forms-pdf-extended#1293]
**Description**
Upload field won't show the path of the selected file from Media Library when merge-tag is activated. You can only select the file by pasting the path itself on the field.

**Step To Reproduce**
1. Go to Template Tab where an Upload Field with merge-tag is present
2. Click on Upload Button
3. Select an image
4. You will now see that the selected file is not showing on the field

**Expected behavior**
The user should be able to choose a file using the Upload button, and/or from the merge-tag selection.

**Screenshots**
![image](https://user-images.githubusercontent.com/35588091/123903145-b59ea580-d9a0-11eb-9158-e52f1971f136.png)

**Additional context**

**Comment by jakejackson1** [comment]
Wasn't able to replicate in latest version (6.1).
