### ISSUE TITLE
Notifications>Add Media>Insert into Post = Broken with No conflict mode "On"

### ISSUE THREAD

**Issue by ewb-git** [blueliquiddesigns/gravity-forms-pdf-extended#1294]
Please reference: https://github.com/GravityPDF/gravity-pdf/issues/1175

This is still causing an issue. Turning off "No conflict mode" fixes this as mentioned in the referenced post.

If I go to form>notifications>add media, the "insert into post" option is greyed out, with "Uncaught TypeError: Cannot read property 'removeAllPlayers' of undefined" in console. Turning off "No conflict mode" allows me to add media to notifications. I would consider this bug, "NOT FIXED".

**Comment by jakejackson1** [comment]
Hi there,

No settings on the page you mentioned are managed by Gravity PDF. You can double check this by disabling Gravity PDF and trying to replicate the problem. If the problem persists you should report this to Gravity Forms directly.
