### ISSUE TITLE
Resolve Repeater display issues and PHP notices

### ISSUE THREAD

**Issue by jestonihpi** [blueliquiddesigns/gravity-forms-pdf-extended#1303]
**Description**
![image](https://user-images.githubusercontent.com/434866/144542088-ff2cd7e4-ef89-4e3e-8116-169d6c2b4daa.png)
When generating the PDF on a form with a `Reapeter` field added. The formatting will throw a Warning error. 

**Step To Reproduce**
Make sure you enable the Debug settings on `wp-config.php`
1. Install Reapeter Add on and create a sample form for it.
2. Add a demo entry and assign the Form's PDF settings in any of the Core templates (Zadani)
3. View the sample entry.

**Expected behavior**
Repeater field should be passed as string? (Not sure how to do it atm)

**Screenshots**

**Additional context**
Upon working with Xdebug the `$string` passed on `wp_check_invalid_utf8() -> formatting.php` contains an array:
e.g 
Array
(
    [1006] => Jes Doe
    [1009] => 195.80
    [1008] => 1468.53
    [1010] => 16153.85
    [1007] => 32307.69
    [1014] => 82.5
    [1036] => a:3:{i:0;a:2:{s:11:"Description";s:14:"Sample Percent";s:6:"Amount";s:7:"1615.38";}i:1;a:2:{s:11:"Description";s:3:"SSS";s:6:"Amount";s:6:"200.00";}i:2;a:2:{s:11:"Description";s:10:"PhilHealth";s:6:"Amount";s:6:"100.00";}}
    [1018] => 18069.23
    [1037] => 0
    [1038] => 18069.23
)

**Comment by jakejackson1** [comment]
When using the first sample form found https://docs.gravityforms.com/repeater-fields/#h-sample-forms the PDF will display a PHP notice `Notice: Undefined index: currency in `/gravitypdf/wp-content/plugins/gravity- pdf/src/Helper/Fields/Field_Number.php on line 81`

**Comment by jakejackson1** [comment]
Cannot be replicated with latest version of Gravity PDF. Closing.
