### ISSUE TITLE
mPDF: Cannot upload font "Great Vibes" via Font Manager

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1304]
**Description**
When trying to install https://fonts.google.com/specimen/Great+Vibes using the Font Manager mPDF creates a bunch of PHP notices while checking if the font is OTF-compatible and it fails to be installed (although is uploaded).

**Step To Reproduce**
1. Go to the Font Manager
2. Add a new font
3. Upload Great Vibes TTF file to the Regular section
4. Save

**Expected behavior**
The font successfully uploads and saved

**Additional context**
Testing shows the PHP process just stops during OTF processing. Further debugging will need to be done to determine why.

**Comment by KratosGemini** [comment]
I'm also getting an error for Noto Sans. I wonder if it's the same issue. https://fonts.google.com/noto/specimen/Noto+Sans

**Comment by jakejackson1** [comment]
Also a problem with Poppins https://fonts.google.com/specimen/Poppins

**Comment by jakejackson1** [comment]
Have opened a PR upstream to fix the problem installing Great Vibes, Noto Sans, and Poppins. Once merged, we'll cut a new release with the fix.

**Comment by jakejackson1** [comment]
This specific issue has been fixed in Gravity PDF 6.5.1. Note, there is a different issue that does affect some font variants (from this list: Noto Sans Bold) and we've opened another issue about it on GitHub: https://github.com/GravityPDF/gravity-pdf/issues/1429
