### ISSUE TITLE
PDF List table issue

### ISSUE THREAD

**Issue by mcglenn07** [blueliquiddesigns/gravity-forms-pdf-extended#1316]
**Description**
The PDF List table is not displaying as a striped-table.

**Step To Reproduce**
1. Go to any Form and activate atleast 2 PDF templates

**Expected behavior**
The PDF List table should be a striped-table.

**Screenshots**
<img width="626" alt="image" src="https://user-images.githubusercontent.com/35588091/153114543-d80a67be-1418-44ed-9564-8a77181c3cce.png">

**Comment by jestonihpi** [comment]
@mcglenn07 . This is due to the class that GF2.6 is using for the table listing. It was updated to ` gf-locking` from `alternative`.  @jakejackson1 I assume we still need to do a backward support for GF2.5? Like what we did with the merge tag and RTE updates.

**Comment by jakejackson1** [comment]
@jestonihpi yes, correct
