### ISSUE TITLE
6.2, Revamp on PDF listing row class (gf-locking/alternate)

### ISSUE THREAD

**Issue by jestonihpi** [blueliquiddesigns/gravity-forms-pdf-extended#1323]
**Description**
We need to re-visit the class changes for the PDF List rows. Previously we added an `if` statement that toggles `alternate` and `gf-locking` depending on the current version of Gravity Forms (`gf-locking` was applied to 2.6-rc-x versions).

**Step To Reproduce**
1. Go to 'Forms->Settings'
2. Click on 'PDF'
3. Scroll down to 'PDF List'
4. Inspect error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jakejackson1** [comment]
Fixed https://github.com/GravityPDF/gravity-pdf/pull/1324
