### ISSUE TITLE
Ensure PDF is saved when using gfpdf_post_save_pdf hook with Background Processing enabled

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1332]
A recent change to the submission flow may have caused the PDF to not be saved when background processing is enabled.

**Comment by jakejackson1** [comment]
@jestonihpi we'll need to modify the queue controller to handle this specific use case https://github.com/GravityPDF/gravity-pdf/blob/development/src/Controller/Controller_Pdf_Queue.php

**Comment by jestonihpi** [comment]
Copy @jakejackson1.
