### ISSUE TITLE
Cannot enable user/editor access to a form's PDF settings without exposing GF's plugin settings

### ISSUE THREAD

**Issue by thomasfw** [blueliquiddesigns/gravity-forms-pdf-extended#1342]
#### Description
As far as I can tell there's no way to allow certain users to access/configure a form's PDF settings (**Dashboard > Form > Settings > PDF**) without giving them the `gravityforms_edit_settings` cap, which opens up the Gravity Forms plugin configuration under **Dashboard > Gravity Forms > Settings**.

In contrast, the default GF form settings (e.g. **Form Settings**, **Confirmations**, **Notifications**) only require the `gravityforms_edit_forms` cap. This allows website editors and other users/roles with limited permissions to access a form's settings pages without also allowing them to mess with the GF plugin configuration. 

#### Step To Reproduce
N/A

#### Expected behavior
We should be able to allow access to a form's PDF settings pages without exposing plugin settings pages.

Assuming you want to maintain backwards compatibility here and aren't willing to switch `gravityforms_edit_settings` for `gravityforms_edit_forms`, maybe you can provide a filter that we can use to override the cap check? 

#### Screenshots
N/A

#### Additional context
N/A

**Comment by jakejackson1** [comment]
Thanks for reporting this. We'll look at possible solutions for an up coming release.
