### ISSUE TITLE
mPDF: PHP Warning when using Font Installer

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1383]
**Description**

Trying to install Poppins from Google Fonts causes the following error to occur on PHP7.4:

```
count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/gravity-forms-pdf-extended/vendor_prefixed/mpdf/mpdf/src/TTFontFile.php on line 2511
```

Related https://github.com/GravityPDF/gravity-pdf/issues/1304

**Additional context**
[Poppins.zip](https://github.com/GravityPDF/gravity-pdf/files/9177038/Poppins.zip)

**Comment by jestonihpi** [comment]
Hi @jakejackson1, I was able to replicate this issue on my end as well :
![image](https://user-images.githubusercontent.com/434866/193973648-4a6a0a64-e100-4d0e-82ff-d6b23a48ff55.png)

**Comment by jakejackson1** [comment]
Related to https://github.com/GravityPDF/gravity-pdf/issues/1304
