### ISSUE TITLE
Background Processing Conflict with WooCommerce GF Add-on

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1403]
**Description**
When the background processing feature is enabled in Gravity PDF and a Notification is sent using the Woo GF add-on after checkout via the `GFAPI::send_notifications()` API, a critical error is shown in the Gravity PDF logs and the notification email isn't sent.

**Comment by jestonihpi** [comment]
Hi @jakejackson1. I may need some help on how to replicate this : Is this the correct Add-on? 
![image](https://user-images.githubusercontent.com/434866/186299460-46191f2c-8c8c-4a0d-9786-e7ab92cfb000.png)
 I have installed woo and set up a demo product with no luck.

**Comment by jestonihpi** [comment]
Updates @jakejackson1 . I think I have now properly set up my Woo addon. Another thing was I cant find any error on the logs :
![image](https://user-images.githubusercontent.com/434866/186312198-628ee7bf-45e0-43c1-ad0a-378b1ecaf325.png)

It seems I need to enable the notification though :
![image](https://user-images.githubusercontent.com/434866/186312291-4751caca-4c20-46d9-ac8c-0f24b56719f3.png)

**Comment by jestonihpi** [comment]
Hi @jakejackson1. Unfortunately I was not able to replicate this issue on my end :
![image](https://user-images.githubusercontent.com/434866/186321626-e6d0c507-beb4-48dc-80dd-e9f59dca5f7d.png)

I may need some assistance on this ticket.

Thanks.

**Comment by jakejackson1** [comment]
@jestonihpi sorry, I created this issue real quick and didn't fill in all the details.

[When linking the Woo Product to a Gravity Forms](https://woocommerce.com/document/woocommerce-gravity-forms-product-addons/#section-17), you will need to enable the "Update Payment and Transaction Details" and "Send Notifications" options.

On the form itself, configure a PDF that attaches to a configured Notification email.

Turn on the PDF Background Processing Feature.

Purchase the Woo Product with the GF Attached and complete the checkout process.

**Comment by jestonihpi** [comment]
Thanks for the clarification @jakejackson1.

**Comment by jestonihpi** [comment]
Hi 
[14003.log](https://github.com/GravityPDF/gravity-pdf/files/9486336/14003.log)
@jakejackson1 , can you verify this file if its the same log in your end?

Thanks.

**Comment by jakejackson1** [comment]
Could not replicate in latest version
