### ISSUE TITLE
GF Addon Chained Select needs improvements.

### ISSUE THREAD

**Issue by jestonihpi** [blueliquiddesigns/gravity-forms-pdf-extended#1411]
**Description**
If you insert GF Chained Select Field on a 4/4 columns. On the PDF the labels need an extra space to aligned with the value.
Also, we need to **mirror** this field settings on the **PDF.**
**Step To Reproduce**
1.Install GF Chained Selects Addon
2. Create Form then Add GF Chain Select field on 4/4 column set up.
3. Submit an entry, and  assign any of the core templates
4. Check the PDF to see the error.

**Expected behavior**
Like the other field, labels and values should be properly aligned **based** on the **field settings.** 
![image](https://user-images.githubusercontent.com/434866/190947761-acd2a8d9-43e2-432c-8f73-e726cc797213.png)
![image](https://user-images.githubusercontent.com/434866/190947726-a313201d-55c2-408d-883f-07212150f736.png)

**Screenshots**
Labels **overlapping**: 
![image](https://user-images.githubusercontent.com/434866/190947086-30ec95e4-9760-4e82-9fd2-1f6341b53215.png)

Working as expected on **1/3** and **1/2**
![image](https://user-images.githubusercontent.com/434866/190947163-cade9a51-e3d1-48e8-91b3-0007f62284f5.png)

**Additional context**
We should add a **new** Helper class under Fields for **Chained Selects**

**Comment by jakejackson1** [comment]
Edge-case.
