### ISSUE TITLE
Consent field showing up in Core PDF when not checked

### ISSUE THREAD

**Issue by jakejackson1** [blueliquiddesigns/gravity-forms-pdf-extended#1450]
**Description**
If a Consent field has a value in the "Description" setting, it will always be considered _not empty_ by Gravity PDF, even if a user didn't check the consent checkbox. This is contrary to how Gravity Forms handles consent fields in the Entry Details page, which always treats unticked Consent fields as empty.

**Step To Reproduce**
1. Add a Consent field to your form and include a value in the "Description" setting.
2. Add a Name field to your form and then save.
3. Setup a Core PDF on the form and ensure the _Show Empty Fields_ option is disabled
4. Submit the form and leave the Consent field unchecked
4. View the PDF

**Expected behavior**
The Consent field would not be shown in the PDF. Currently, it is showing.

**Screenshots**
<img width="919" alt="Screenshot 2023-02-17 at 9 23 16 am" src="https://user-images.githubusercontent.com/2918419/219500662-dc788d41-6af7-4c09-8cef-fd32de3c5a92.png">

**Comment by jestonihpi** [comment]
Replicated this issue on my end @jakejackson1 
![image](https://user-images.githubusercontent.com/434866/223582291-6b24e002-af31-4d54-bb6b-f678fad2bcac.png)
