### ISSUE TITLE
Newly created PDF settings revert when updating form in different window

### ISSUE THREAD

**Issue by dantabifranca** [blueliquiddesigns/gravity-forms-pdf-extended#1469]
**Description**
If you update a form in a different window while simultaneously saving a newly created PDF for that form, the settings for the PDF will revert to an empty slate.

**Step To Reproduce**
1. Open a window with the Form Editor (Window A) and open a new window with the PDF list for that form opened (Window B).
2. Add a new PDF in Window B and save it.
3. Make any changes in Window A and save the form.
4. Go back to Window B and do a hard refresh.
5. The PDF will be reverted to an empty slate.
6. Still in Window B, navigate to the PDF list, and you will find the newly created PDF saved there.

**Expected behavior**
The PDF settings for the newly created PDF should be reverted to an empty slate, but it should still be saved in the PDF list.

**Screen Recording**
https://github.com/GravityPDF/gravity-pdf/assets/70549540/f7747e10-9bcd-49a0-85e1-4f2887ac7df7

**Comment by jakejackson1** [comment]
@dantabifranca you'll find this has nothing to do with multiple windows open. When adding a new PDF, after you submit and it first gets saved, if you then refresh, the UI will act like it is adding a new PDF once again. The PDF you just saved will still be saved though, and can be accessed from the PDF List page.
