### ISSUE TITLE
Uncaught ValueError: str_repeat() in the Gravity PDF 6.12.2

### ISSUE THREAD

**Issue by mcglenn07** [blueliquiddesigns/gravity-forms-pdf-extended#1586]
**Description**
Once version 6.12.2 is installed (canonical), after sometime the site will display critical error. The complete error message was "Fatal error: Uncaught ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to O in C:laragon\www\wp\wp-content\plugins\gravity-pdf\gravity-pdf-updater.php on line 58"

**Step To Reproduce**
1. Install the 6.12.2 version;
2. It takes some time before it throws the error. Usually, it occurs after logging out and then logging back in.

**Expected behavior**
When the latest version of Gravity PDF is installed, it should not cause any critical error to the site.

**Screenshots**
![image](https://github.com/user-attachments/assets/3ef1e22d-9342-4cbf-ada0-15e45709f9dd)

**Comment by jakejackson1** [comment]
Resolved in 6.12.3
