### ISSUE TITLE
Consider changing list field htmlspecialchars to strip_tags to cater for a href links

### ISSUE THREAD

**Issue by ovann86** [blueliquiddesigns/gravity-forms-pdf-extended#5]
I'm developing a plugin for Gravity Forms that converts URL's entered into the the 'list field' to clickable links in the back end.

I'm doing this by storing the values in the database as an HTML link.

For example, if the user enters 

`www.google.com`

The plugin will store the value in the database as:

`<a href="www.google.com">www.google.com</a>`

I need to display the link as a clickable link in the PDF created by this plugin. However I found that pdf-entry-detail.php at line 2002 escapes the HTML before it's put in the PDF. So the code pulled into mPDF is turned into:

`&lt;a href="www.google.com"&gt;www.google.com&lt;/a&gt;`

I agree that the HTML needs to be escaped to stop users breaking the PDF by entering in table tags like </td> or </table> - but I would like to ask if you could consider changing this to allow links.

The change would be - pdf-entry-detail.php - line 2002

FROM

`$list .= '<td>'.htmlspecialchars($val).'</td>';`

TO

`$list .= '<td>'.strip_tags($val,'<a>').'</td>';`

Please let me know if this is a possibility, otherwise I will need to consider my options (other ways of creating PDF's, customising the plugin after each update/providing instructions on how to modify the plugin).

Thanks,

**Comment by blueliquiddesigns** [comment]
I'm not sure using `strip_tags()` is a good idea as it can remove valid user input (http://stackoverflow.com/a/3605944).

Our aim with the default PDF templates is to make the output as similar to Gravity Forms as possible. Currently they don't support HTML in list fields so we don't plan to by default either. 

You could always create a custom PDF template and parse the list field as you require but that would only work well on sites you have control of. 

The `$display_value` does run through the `gform_entry_field_value` filter on line 255 which you could use in your plugin by running through the HTML DOM and parse the text as needed.

**Comment by ovann86** [comment]
That's a very good point.

I did feel kind of funny about storing the links are formatted HTML, so this is an even better solution to the whole requirement - thank you!
