### ISSUE TITLE
View & Download PDF always regenerates PDF

### ISSUE THREAD

**Issue by fgl87** [blueliquiddesigns/gravity-forms-pdf-extended#7]
The part of pdf-render.php at the bottom of this message isn't working properly, resulting in unnecessary regeneration of already existing PDF files (located in the output folder).

`$pdf_creator` is always empty, because it never gets defined after it's created on `line 44`.
Therefore the conditions of the IF-statement never return `true`, so PDFs are always being regenerated despite the fact that the file might already be present in the output folder.

I forced the IF-statement to return `true`, but the returned value still doesn't load the existing PDF in the opening browser tab.

Any solution to this would be greatly appreciated.

```php
		/* 
		 * Check if the PDF exists and if this function has already run this season 
		 */	
		if(in_array($lead_id, $pdf_creator) && file_exists($gfpdfe_data->template_save_location . $id . '/' . $filename))
		{					
			/* 
			 * Don't generate a new PDF, use the existing one 
			 */
			 
			return $gfpdfe_data->template_save_location . $id . '/' . $filename;	
		}
```

**Comment by blueliquiddesigns** [comment]
The `$pdf_creator` is only used if a PDF has already been generated in that request. For example, if the PDF should be attached to multiple notifications it won't regenerate the PDF a second time. 

There is currently no caching system in place for the PDFs so the PDF is regenerated upon each request.
